### ISSUE TITLE
Time out waiting for Start ACK (WireFlow)

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/build-support#5]
![image](https://user-images.githubusercontent.com/26659428/172189206-2020d319-626e-4f18-9488-d4575e1e67e3.png)

This happens intermittently. Not clear why

**Comment by ciozi137** [comment]
I made my own progress bar based on SMOs;
![image](https://user-images.githubusercontent.com/26659428/172398283-7a061647-ae70-4645-a06f-eb5253ba6ca8.png)

![2022-06-07_9-58-29](https://user-images.githubusercontent.com/26659428/172399210-2d0303bf-25e3-441a-8371-94e1ef542565.gif)

Perhaps this will fix the issue with WireFlow Progress bar...or at least make debugging easier

**Comment by Monkeymerlot** [comment]
This will definitely be more flexible.
